import type { Metadata } from 'next';
import ServicePageTemplate from '../../components/services/ServicePageTemplate';

export const metadata: Metadata = {
  title: 'Influencer Marketing | Noplin Digital',
  description: 'Professional Influencer Marketing services tailored to elevate your business.',
};

export default function ServicePage() {
  return (
    <ServicePageTemplate
      serviceName="Influencer Marketing"
      department="Marketing"
      tagline="Professional Influencer Marketing services tailored to elevate your business."
      turnaround="1–2 Weeks"
      heroImage="https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2000&auto=format&fit=crop"
      about="Our Influencer Marketing offering is designed to provide you with the exact tools and expertise you need to succeed online. We focus on delivering high-quality, conversion-optimized results that align perfectly with your core objectives."
      whatItIncludes={[
  {
    title: "Influencer Discovery & Vetting Report",
    description: "A curated shortlist of rigorously vetted influencers aligned with your brand values, audience demographics, and engagement quality rather than raw follower count.",
    icon: "magnifier",
    color: "purple"
  },
  {
    title: "Campaign Brief & Creative Guidelines",
    description: "A comprehensive creative brief giving influencers clear messaging direction while allowing authentic expression, ensuring content feels native rather than overtly promotional.",
    icon: "document",
    color: "yellow"
  },
  {
    title: "Performance Tracking Dashboard",
    description: "Real-time visibility into reach, engagement rate, swipe-up clicks, promo code redemptions, and attributable revenue generated by each individual influencer partnership.",
    icon: "chart",
    color: "green"
  }
]}
      whoItsFor="Perfect for businesses, founders, and ambitious teams looking to establish a dominant presence and scale operations with top-tier Influencer Marketing."
      process={[
  {
    step: "01",
    title: "Define ideal influencer profile",
    description: "We work with you to build the exact criteria for potential partners niche alignment, minimum engagement rate, audience demographic breakdown, and geographic focus."
  },
  {
    step: "02",
    title: "Research & vet candidate list",
    description: "We identify and deeply audit potential influencers, checking for fake follower patterns, audience authenticity scores, content quality, and brand safety history."
  },
  {
    step: "03",
    title: "Negotiate partnership terms",
    description: "We handle all outreach, rate negotiation, deliverable agreements, and legal contract prep so you are protected and paying fair market rates for genuine reach."
  },
  {
    step: "04",
    title: "Develop campaign creative brief",
    description: "We craft a crystal-clear brief that gives influencers the messaging pillars, required disclosures, key talking points, and visual guidelines while preserving their authentic voice."
  },
  {
    step: "05",
    title: "Manage content review & approval",
    description: "Before anything goes live, influencer content passes through our review process to verify brand safety, disclosure compliance, and messaging accuracy."
  },
  {
    step: "06",
    title: "Track performance & report results",
    description: "We monitor all live posts in real time, capturing reach, engagement, trackable clicks, and promo code usage to calculate true campaign ROI and inform future partnerships."
  }
]}
      complementaryServices={[
  {
    name: "Social Media Management",
    url: "/services/social-media-management",
    desc: "Maintain active, professional social profiles so every influencer-driven visitor arrives at a credible, engaging brand presence."
  },
  {
    name: "Ad Creatives (Video)",
    url: "/services/ad-creatives-video",
    desc: "Repurpose the best-performing influencer video content into paid ads to dramatically extend its reach beyond the influencer's existing audience."
  },
  {
    name: "Landing Page Design",
    url: "/services/landing-page-design",
    desc: "Direct campaign traffic to a dedicated, conversion-optimized landing page that captures leads and conversions generated by influencer promotion."
  }
]}
      faqs={[
  {
    question: "How do you find the right influencers?",
    answer: "We use a combination of platform analytics tools and manual research to identify influencers whose audience demographics and engagement quality genuinely match your target customer profile."
  },
  {
    question: "Is follower count the most important metric?",
    answer: "No. Engagement rate is far more important. A micro-influencer with 15,000 highly engaged followers in your niche will consistently outperform a celebrity with a passive million-follower audience."
  },
  {
    question: "How do you track ROI from influencer posts?",
    answer: "We use unique trackable links, custom promo codes, and UTM parameters so every click, signup, or purchase generated by each specific influencer is attributed accurately."
  },
  {
    question: "Do you manage nano and micro influencers?",
    answer: "Yes. We specialize in micro-influencer campaigns involving creators with 10,000 to 200,000 followers because this tier consistently delivers the highest engagement and conversion rates per dollar spent."
  },
  {
    question: "Do you handle the legal contracts with influencers?",
    answer: "Yes. We prepare standardized partnership agreements covering content usage rights, exclusivity clauses, performance deliverables, and FTC disclosure requirements for every campaign."
  },
  {
    question: "Can influencer marketing work for B2B brands?",
    answer: "Absolutely. LinkedIn thought leaders and podcast hosts in your industry are highly effective B2B influencers for generating qualified leads and positioning you as an authority."
  }
]}
    />
  );
}
