import type { Metadata } from 'next';
import ServicePageTemplate from '../../components/services/ServicePageTemplate';

export const metadata: Metadata = {
  title: 'Ad Creatives (Video) | Noplin Digital',
  description: 'Professional Ad Creatives (Video) services tailored to elevate your business.',
};

export default function ServicePage() {
  return (
    <ServicePageTemplate
      serviceName="Ad Creatives (Video)"
      department="Design"
      tagline="Professional Ad Creatives (Video) services tailored to elevate your business."
      turnaround="48 Hours"
      heroImage="https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=2000&auto=format&fit=crop"
      about="Our Ad Creatives (Video) offering is designed to provide you with the exact tools and expertise you need to succeed online. We focus on delivering high-quality, conversion-optimized results that align perfectly with your core objectives."
      whatItIncludes={[
  {
    title: "2–4 Short Video Ads",
    description: "Highly engaging, fast-paced video creatives specifically formatted for massive reach on Reels, TikTok, and YouTube Shorts.",
    icon: "play",
    color: "pink"
  },
  {
    title: "Dynamic Captions",
    description: "Eye-catching, hardcoded captions embedded directly into the video to capture the 80% of users who watch their feeds with the sound off.",
    icon: "chat",
    color: "yellow"
  },
  {
    title: "Suggested Ad Copy",
    description: "Proven, high-converting primary text formulated by our direct-response copywriters to accompany your video ad and drive immediate clicks.",
    icon: "pen",
    color: "green"
  }
]}
      whoItsFor="Perfect for businesses, founders, and ambitious teams looking to establish a dominant presence and scale operations with top-tier Ad Creatives (Video)."
      process={[
  {
    step: "01",
    title: "Get Ad Brief & Brand Assets",
    description: "We gather all necessary brand assets, product information, and your specific campaign goals to establish a strong foundation for the creative strategy."
  },
  {
    step: "02",
    title: "Write video script/concept",
    description: "Our copywriters craft compelling hooks, engaging scripts, and strong calls-to-action tailored to capturing attention within the first 3 seconds."
  },
  {
    step: "03",
    title: "Edit & add text overlays/music",
    description: "We meticulously edit the footage, integrating dynamic text overlays, trending audio, and seamless transitions optimized for platforms like Reels and TikTok."
  },
  {
    step: "04",
    title: "Client review & approval",
    description: "You review the draft videos. We take your feedback and refine the pacing, captions, and visual elements until they are ready to convert."
  },
  {
    step: "05",
    title: "Deliver final files",
    description: "We hand over the final, platform-optimized mp4 files along with suggested, high-converting ad copy ready for immediate deployment."
  }
]}
      complementaryServices={[
  {
    name: "Social Media Ads Management",
    url: "/services/social-media-ads-management",
    desc: "Let our media buyers deploy and manage your new video creatives to maximize your ROI."
  },
  {
    name: "Landing Page Design",
    url: "/services/landing-page-design",
    desc: "Ensure the traffic generated by your video ads lands on a high-converting, targeted page."
  },
  {
    name: "Ad Creatives (Image)",
    url: "/services/ad-creatives-image",
    desc: "A/B test your video campaigns alongside high-performing static image ads."
  }
]}
      faqs={[
  {
    question: "Do I need to provide the raw video footage?",
    answer: "You can provide raw footage of your product/service, or we can utilize high-quality stock footage and motion graphics depending on your campaign needs."
  },
  {
    question: "What video formats do you deliver?",
    answer: "We typically deliver 9:16 vertical videos for Reels/TikTok/Shorts, and 1:1 or 4:5 ratios for standard feed placements."
  },
  {
    question: "Do you include voiceovers in the ad creatives?",
    answer: "Yes! We can include professional AI voiceovers, or utilize trending audio/background tracks to maximize platform engagement."
  },
  {
    question: "How long are the video ads usually?",
    answer: "For direct response marketing on social platforms, we aim for punchy 15 to 30-second videos to maintain viewer retention."
  },
  {
    question: "Are captions hardcoded into the video?",
    answer: "Yes, we embed dynamic, easy-to-read captions directly into the video to capture the 80% of users who watch with the sound off."
  },
  {
    question: "Can you run the ads for us as well?",
    answer: "Yes, we offer full-service Social Media Ads Management if you need experts to handle the media buying and ad account management."
  }
]}
    />
  );
}
