import type { Metadata } from 'next';
import ServicePageTemplate from '../../components/services/ServicePageTemplate';

export const metadata: Metadata = {
  title: 'Ad Creatives (Image) | Noplin Digital',
  description: 'Professional Ad Creatives (Image) services tailored to elevate your business.',
};

export default function ServicePage() {
  return (
    <ServicePageTemplate
      serviceName="Ad Creatives (Image)"
      department="Design"
      tagline="Professional Ad Creatives (Image) services tailored to elevate your business."
      turnaround="24 Hours"
      heroImage="https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=2000&auto=format&fit=crop"
      about="Our Ad Creatives (Image) offering is designed to provide you with the exact tools and expertise you need to succeed online. We focus on delivering high-quality, conversion-optimized results that align perfectly with your core objectives."
      whatItIncludes={[
  {
    title: "3-5 High-Converting Graphics",
    description: "Thumb-stopping static graphics that balance aesthetic appeal with proven direct-response marketing principles to lower your cost-per-click.",
    icon: "target",
    color: "amber"
  },
  {
    title: "Format Variations",
    description: "Perfectly cropped variants adapted precisely for Facebook Feeds, Instagram Stories, LinkedIn, and Google Display dimensions.",
    icon: "monitor",
    color: "purple"
  },
  {
    title: "Split-Test Ad Copy",
    description: "Multiple variations of punchy primary text and headlines designed to be A/B tested to find your winning message.",
    icon: "pen",
    color: "blue"
  }
]}
      whoItsFor="Perfect for businesses, founders, and ambitious teams looking to establish a dominant presence and scale operations with top-tier Ad Creatives (Image)."
      process={[
  {
    step: "01",
    title: "Understand the Project",
    description: "We conduct a discovery phase to understand your offer, target audience, and the unique selling propositions you want to highlight."
  },
  {
    step: "02",
    title: "Craft ad text/message",
    description: "Our direct-response copywriters formulate punchy headlines and compelling body copy designed specifically to drive clicks."
  },
  {
    step: "03",
    title: "Send to Designer",
    description: "The creative brief and approved copy are handed off to our design team to start the visual conceptualization process."
  },
  {
    step: "04",
    title: "Designer produces creatives",
    description: "Our designers create thumb-stopping graphics that balance aesthetic appeal with proven direct-response marketing principles."
  },
  {
    step: "05",
    title: "Send to Client for Approval",
    description: "We present the static ad concepts to you for feedback, ensuring they align perfectly with your brand voice and visual standards."
  },
  {
    step: "06",
    title: "Deliver final files",
    description: "High-resolution files are delivered in perfect aspect ratios for Meta, LinkedIn, or Google, along with corresponding primary text variations."
  }
]}
      complementaryServices={[
  {
    name: "Social Media Ads Management",
    url: "/services/social-media-ads-management",
    desc: "Deploy your new image ads through our expert media buying team for maximum returns."
  },
  {
    name: "Sales Funnel Design",
    url: "/services/sales-funnel-design",
    desc: "Build an optimized funnel to reliably convert the clicks generated by your new ads."
  },
  {
    name: "Ad Creatives (Video)",
    url: "/services/ad-creatives-video",
    desc: "Diversify your ad account by adding engaging short-form video creatives to the mix."
  }
]}
      faqs={[
  {
    question: "What platforms are these image ads optimized for?",
    answer: "We design specifically for the platforms you are targeting, primarily Meta (Facebook/Instagram), LinkedIn, X, and Google Display."
  },
  {
    question: "Do you use my product photos or stock images?",
    answer: "We prefer to use high-quality photos of your actual products, but we have access to premium stock libraries if needed to supplement the design."
  },
  {
    question: "How many copy variations do you provide?",
    answer: "We typically provide 2-3 primary text variations for each graphical ad, allowing you to split-test messaging."
  },
  {
    question: "What makes your ad creatives different from regular posts?",
    answer: "Regular posts are for engagement; ad creatives are engineered specifically for conversion, utilizing psychological triggers, clear CTAs, and optimized visual hierarchy."
  },
  {
    question: "Do you guarantee a certain click-through rate (CTR)?",
    answer: "While we design using proven high-converting strategies, CTR depends heavily on audience targeting and budget, which we cover in our Ads Management service."
  }
]}
    />
  );
}
